version: '3.4'

services:
  webapi.registercustomer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32033:80"   
    networks:
        - teste2
     
networks:
  teste2:
    driver: bridge